# Generated by Django 6.1 on 2026-10-07 23:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeocodeCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=500, unique=True, verbose_name='строка запроса')),
                ('found', models.BooleanField(default=False, verbose_name='найдено')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='широта')),
                ('lon', models.FloatField(blank=True, null=True, verbose_name='долгота')),
                ('rank', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ранг места')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='когда спросили')),
            ],
            options={
                'verbose_name': 'ответ геокодера',
                'verbose_name_plural': 'кэш геокодера',
                'ordering': ['-created_at'],
            },
        ),
    ]
