# Generated by Django 6.1 on 2026-08-19 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_encrypted', models.TextField(editable=False, verbose_name='секрет (шифр)')),
                ('tail4', models.CharField(default='', editable=False, max_length=4, verbose_name='последние 4 символа')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('username', models.CharField(blank=True, max_length=100, verbose_name='@username')),
                ('is_active', models.BooleanField(default=False, verbose_name='активный')),
                ('checked_at', models.DateTimeField(blank=True, null=True, verbose_name='проверен')),
                ('check_ok', models.BooleanField(blank=True, null=True, verbose_name='проверка прошла')),
            ],
            options={
                'verbose_name': 'Telegram-бот',
                'verbose_name_plural': 'Telegram-боты',
            },
        ),
        migrations.CreateModel(
            name='BotSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_detailed', models.TextField(blank=True, help_text='Пусто — бот использует свой встроенный текст', verbose_name='промпт развёрнутого режима')),
                ('prompt_chat', models.TextField(blank=True, verbose_name='промпт диалогового режима')),
                ('invent_facts', models.BooleanField(default=True, help_text='Режим показа. Для настоящих обращений выключить: бот будет опираться только на справочник контактов', verbose_name='разрешать додумывать факты')),
                ('enabled', models.BooleanField(default=True, verbose_name='бот включён')),
                ('maintenance_text', models.CharField(default='Бот временно недоступен: идут технические работы. Пожалуйста, напишите позже.', max_length=300, verbose_name='текст при выключенном боте')),
                ('default_provider', models.CharField(choices=[('openai', 'GPT (OpenAI)'), ('gemini', 'Gemini (Google)'), ('claude', 'Claude (Anthropic)')], default='openai', max_length=16, verbose_name='провайдер по умолчанию')),
                ('version', models.PositiveIntegerField(default=1, editable=False, verbose_name='версия')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'настройки бота',
                'verbose_name_plural': 'настройки бота',
            },
        ),
        migrations.CreateModel(
            name='Heartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('providers', models.JSONField(default=dict, verbose_name='состояние провайдеров')),
                ('counters', models.JSONField(default=dict, verbose_name='счётчики')),
            ],
            options={
                'verbose_name': 'сердцебиение',
                'verbose_name_plural': 'сердцебиения',
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
            },
        ),
        migrations.CreateModel(
            name='Outbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(verbose_name='chat id получателя')),
                ('text', models.TextField(verbose_name='текст')),
                ('kind', models.CharField(choices=[('reply', 'Ответ жителю'), ('broadcast', 'Рассылка'), ('notify', 'Уведомление сотрудникам')], max_length=16, verbose_name='вид')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('sent', 'Отправлено'), ('failed', 'Не доставлено')], default='pending', max_length=16, verbose_name='состояние')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='попыток')),
                ('error', models.CharField(blank=True, max_length=300, verbose_name='ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'исходящее',
                'verbose_name_plural': 'исходящие',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProviderKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_encrypted', models.TextField(editable=False, verbose_name='секрет (шифр)')),
                ('tail4', models.CharField(default='', editable=False, max_length=4, verbose_name='последние 4 символа')),
                ('provider', models.CharField(choices=[('openai', 'GPT (OpenAI)'), ('gemini', 'Gemini (Google)'), ('claude', 'Claude (Anthropic)')], max_length=16, unique=True, verbose_name='провайдер')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='модель')),
                ('is_active', models.BooleanField(default=True, verbose_name='используется')),
                ('last_check_ok', models.BooleanField(blank=True, null=True, verbose_name='проверка прошла')),
                ('last_check_at', models.DateTimeField(blank=True, null=True, verbose_name='проверен')),
            ],
            options={
                'verbose_name': 'ключ провайдера',
                'verbose_name_plural': 'ключи провайдеров',
            },
        ),
        migrations.CreateModel(
            name='QuickAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggers', models.TextField(help_text='По одной на строку. Совпадение без учёта регистра, по вхождению', verbose_name='фразы-триггеры')),
                ('answer', models.TextField(verbose_name='ответ')),
                ('is_active', models.BooleanField(default=True, verbose_name='действует')),
                ('hits', models.PositiveIntegerField(default=0, verbose_name='срабатываний')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'готовый ответ',
                'verbose_name_plural': 'готовые ответы',
            },
        ),
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='текст')),
                ('audience', models.CharField(choices=[('all', 'Все, кто писал боту'), ('district', 'Жители района'), ('category', 'Обращавшиеся по категории')], default='all', max_length=16, verbose_name='кому')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('queued', 'В очереди'), ('sending', 'Отправляется'), ('done', 'Завершена')], default='draft', max_length=16, verbose_name='состояние')),
                ('total', models.PositiveIntegerField(default=0, verbose_name='получателей')),
                ('sent', models.PositiveIntegerField(default=0, verbose_name='отправлено')),
                ('failed', models.PositiveIntegerField(default=0, verbose_name='не доставлено')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='directory.category', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
                'ordering': ['-created_at'],
            },
        ),
    ]
