# Generated by Django 6.1 on 2026-08-19 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('botcontrol', '0001_initial'),
        ('directory', '0001_initial'),
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcast',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='кто создал'),
        ),
        migrations.AddField(
            model_name='broadcast',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='directory.district', verbose_name='район'),
        ),
        migrations.AddField(
            model_name='outbox',
            name='broadcast',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outbox', to='botcontrol.broadcast'),
        ),
        migrations.AddField(
            model_name='outbox',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbox', to='tickets.ticket'),
        ),
        migrations.AddIndex(
            model_name='outbox',
            index=models.Index(fields=['status', 'created_at'], name='botcontrol__status_585bc0_idx'),
        ),
    ]
