# Generated by Django 6.1 on 2026-08-20 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botcontrol', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botsetting',
            name='default_provider',
            field=models.CharField(choices=[('openai', 'GPT (OpenAI)'), ('gemini', 'Gemini (Google)'), ('claude', 'Claude (Anthropic)'), ('openrouter', 'OpenRouter')], default='openai', max_length=16, verbose_name='провайдер по умолчанию'),
        ),
        migrations.AlterField(
            model_name='providerkey',
            name='provider',
            field=models.CharField(choices=[('openai', 'GPT (OpenAI)'), ('gemini', 'Gemini (Google)'), ('claude', 'Claude (Anthropic)'), ('openrouter', 'OpenRouter')], max_length=16, unique=True, verbose_name='провайдер'),
        ),
    ]
