# Generated by Django 6.1 on 2026-08-30 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botcontrol', '0003_alter_botsetting_default_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outbox',
            name='channel',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('whatsapp', 'WhatsApp')], default='telegram', max_length=16, verbose_name='канал'),
        ),
    ]
