# Generated by Django 6.1 on 2026-08-19 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=60, verbose_name='действие')),
                ('obj', models.CharField(blank=True, max_length=120, verbose_name='объект')),
                ('summary', models.CharField(blank=True, max_length=300, verbose_name='что именно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='когда')),
            ],
            options={
                'verbose_name': 'запись журнала',
                'verbose_name_plural': 'журнал действий',
                'ordering': ['-created_at'],
            },
        ),
    ]
