# Generated by Django 6.1 on 2026-08-19 19:20

import django.db.models.deletion
import tickets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=tickets.models.attachment_path, verbose_name='файл')),
                ('tg_file_id', models.CharField(blank=True, max_length=200, verbose_name='file_id в Telegram')),
                ('mime', models.CharField(blank=True, max_length=100, verbose_name='тип')),
                ('size', models.PositiveIntegerField(default=0, verbose_name='размер, байт')),
            ],
            options={
                'verbose_name': 'вложение',
                'verbose_name_plural': 'вложения',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=40, verbose_name='что произошло')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='детали')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'событие',
                'verbose_name_plural': 'события',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(choices=[('citizen', 'Житель'), ('ai', 'ИИ'), ('staff', 'Сотрудник'), ('system', 'Система')], max_length=8, verbose_name='автор')),
                ('text', models.TextField(blank=True, verbose_name='текст')),
                ('tg_message_id', models.BigIntegerField(blank=True, null=True, verbose_name='id сообщения в Telegram')),
                ('rating', models.CharField(blank=True, choices=[('up', 'Помогло'), ('down', 'Не помогло')], max_length=4, null=True, verbose_name='оценка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='время')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='текст')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'заметка',
                'verbose_name_plural': 'заметки',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=12, unique=True, verbose_name='номер')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='заголовок')),
                ('description', models.TextField(blank=True, verbose_name='суть обращения')),
                ('address', models.CharField(blank=True, max_length=250, verbose_name='адрес')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='широта')),
                ('lon', models.FloatField(blank=True, null=True, verbose_name='долгота')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('waiting', 'Ждёт ответа'), ('done', 'Выполнена'), ('rejected', 'Отклонена')], default='new', max_length=16, verbose_name='статус')),
                ('answer_mode', models.CharField(choices=[('ai', 'Отвечает ИИ'), ('staff', 'Отвечает сотрудник')], default='ai', max_length=8, verbose_name='кто отвечает')),
                ('due_at', models.DateTimeField(blank=True, null=True, verbose_name='срок исполнения')),
                ('unread', models.BooleanField(default=True, verbose_name='есть непрочитанное')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменена')),
                ('last_message_at', models.DateTimeField(blank=True, null=True, verbose_name='последнее сообщение')),
            ],
            options={
                'verbose_name': 'обращение',
                'verbose_name_plural': 'обращения',
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketCounter',
            fields=[
                ('year', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('value', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_user_id', models.BigIntegerField(unique=True, verbose_name='Telegram user id')),
                ('chat_id', models.BigIntegerField(verbose_name='Telegram chat id')),
                ('first_name', models.CharField(blank=True, max_length=120, verbose_name='имя')),
                ('last_name', models.CharField(blank=True, max_length=120, verbose_name='фамилия')),
                ('username', models.CharField(blank=True, max_length=120, verbose_name='username')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='телефон')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='заблокировал бота')),
                ('subscribed', models.BooleanField(default=True, verbose_name='подписан на рассылки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='впервые написал')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citizens', to='directory.district', verbose_name='район')),
            ],
            options={
                'verbose_name': 'житель',
                'verbose_name_plural': 'жители',
            },
        ),
    ]
