# Generated by Django 6.1 on 2026-08-30 12:02

from django.db import migrations, models
from django.db.models import Count


def check_no_duplicate_channel_chat_id(apps, schema_editor):
    """Страховка перед жёстким constraint: если у двух живых жителей уже
    совпадают (channel, chat_id) — миграция должна упасть с понятной
    ошибкой, а не молча провалить AddConstraint на боевых данных."""
    Citizen = apps.get_model("tickets", "Citizen")
    dupes = (
        Citizen.objects.values("channel", "chat_id")
        .annotate(n=Count("id"))
        .filter(n__gt=1)
    )
    if dupes.exists():
        raise RuntimeError(
            "Найдены жители с одинаковыми (channel, chat_id) — миграция "
            "0003 остановлена перед наложением уникального ограничения: "
            f"{list(dupes)}"
        )


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
        ('tickets', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='channel',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('whatsapp', 'WhatsApp')], default='telegram', max_length=16, verbose_name='канал'),
        ),
        migrations.AddField(
            model_name='citizen',
            name='last_inbound_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='последнее входящее'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='channel',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('whatsapp', 'WhatsApp')], default='telegram', max_length=16, verbose_name='канал'),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='chat_id',
            field=models.BigIntegerField(verbose_name='chat id / номер телефона'),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='tg_user_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Telegram user id'),
        ),
        migrations.RunPython(check_no_duplicate_channel_chat_id, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='citizen',
            constraint=models.UniqueConstraint(fields=('channel', 'chat_id'), name='tickets_citizen_unique_channel_chat_id'),
        ),
    ]
