# Generated by Django 6.1 on 2026-09-17 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_citizen_channel_citizen_last_inbound_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='last_message_preview',
            field=models.CharField(blank=True, max_length=300, verbose_name='превью последнего сообщения'),
        ),
    ]
