# Generated by Django 6.1 on 2026-10-07 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticket_last_message_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='middle_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='отчество'),
        ),
        migrations.AddField(
            model_name='citizen',
            name='name_confirmed',
            field=models.BooleanField(default=False, verbose_name='ФИО назвал сам житель'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='kind',
            field=models.CharField(blank=True, choices=[('appeal', 'Обращение/жалоба'), ('question', 'Справочный вопрос'), ('other', 'Прочее')], default='', max_length=16, verbose_name='тип обращения'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='settlement',
            field=models.CharField(blank=True, max_length=150, verbose_name='населённый пункт'),
        ),
    ]
