# Generated by Django 6.1 on 2026-10-07 23:20

from django.db import migrations, models


def failed_marks_to_geo_source(apps, schema_editor):
    """Старые метки геокодера перевести в новые поля.

    Раньше «адрес не распознан» писали прямо в координаты: lat = lon = -1000.
    Такая заявка была «с координатами» для любого фильтра `lat IS NOT NULL`,
    и каждое место, читающее координаты, обязано было помнить про заглушку.
    Теперь пустые lat/lon значат «точки нет», а причина лежит в geo_source.

    Остальные заявки с настоящими координатами поставил старый геокодер
    (по адресу) — помечаем их так, чтобы карта знала источник точки.
    """
    Ticket = apps.get_model("tickets", "Ticket")
    Ticket.objects.filter(lat__lt=-90).update(lat=None, lon=None, geo_source="failed")
    Ticket.objects.filter(
        lat__isnull=False, lon__isnull=False, geo_source="",
    ).update(geo_source="address")


def geo_source_to_failed_marks(apps, schema_editor):
    """Обратный ход: вернуть заглушку -1000 тем, у кого адрес не распознан."""
    Ticket = apps.get_model("tickets", "Ticket")
    Ticket.objects.filter(geo_source="failed", lat__isnull=True).update(
        lat=-1000.0, lon=-1000.0)


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_citizen_middle_name_citizen_name_confirmed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='geo_query',
            field=models.CharField(blank=True, max_length=300, verbose_name='строка геокодирования'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='geo_source',
            field=models.CharField(blank=True, choices=[('', 'нет'), ('address', 'по адресу'), ('settlement', 'по населённому пункту (примерно)'), ('pin', 'геометка жителя'), ('manual', 'поставил сотрудник'), ('failed', 'адрес не распознан')], default='', max_length=16, verbose_name='источник точки'),
        ),
        migrations.RunPython(failed_marks_to_geo_source, geo_source_to_failed_marks),
    ]
