# Generated by Django 6.1 on 2026-08-19 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('slug', models.SlugField(unique=True, verbose_name='код')),
                ('icon', models.CharField(blank=True, help_text='Имя иконки из static/icons.svg, например road или water', max_length=40, verbose_name='иконка')),
                ('color', models.CharField(default='#5B7DB1', help_text='HEX, используется только фоном чипа в списке', max_length=7, verbose_name='цвет чипа')),
                ('sla_hours', models.PositiveIntegerField(default=72, help_text='Через сколько часов открытая заявка считается просроченной', verbose_name='срок исполнения, часов')),
                ('is_active', models.BooleanField(default=True, verbose_name='действует')),
                ('order', models.PositiveIntegerField(default=100, verbose_name='порядок')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('slug', models.SlugField(unique=True, verbose_name='код')),
                ('is_active', models.BooleanField(default=True, verbose_name='действует')),
            ],
            options={
                'verbose_name': 'район',
                'verbose_name_plural': 'районы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Executor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='полное название')),
                ('short_name', models.CharField(blank=True, max_length=80, verbose_name='короткое название')),
                ('is_active', models.BooleanField(default=True, verbose_name='действует')),
            ],
            options={
                'verbose_name': 'исполнитель',
                'verbose_name_plural': 'исполнители',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('office', 'Отдел / учреждение'), ('person', 'Сотрудник'), ('hotline', 'Горячая линия')], default='office', max_length=16, verbose_name='тип')),
                ('title', models.CharField(max_length=200, verbose_name='название или должность')),
                ('phone', models.CharField(blank=True, max_length=100, verbose_name='телефон')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='адрес')),
                ('work_hours', models.CharField(blank=True, max_length=200, verbose_name='часы работы')),
                ('comment', models.CharField(blank=True, max_length=300, verbose_name='примечание')),
                ('is_public', models.BooleanField(default=True, verbose_name='бот может называть жителям')),
                ('category', models.ForeignKey(blank=True, help_text='Если задана, бот упоминает контакт в ответах на эту тему', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='directory.category', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'контакт',
                'verbose_name_plural': 'контакты',
                'ordering': ['kind', 'title'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='default_executor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='directory.executor', verbose_name='исполнитель по умолчанию'),
        ),
    ]
