# Generated by Django 6.1 on 2026-10-07 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='kind',
            field=models.CharField(blank=True, choices=[('district', 'район'), ('city', 'город областного значения')], max_length=16, verbose_name='вид'),
        ),
        migrations.AddField(
            model_name='executor',
            name='external_id',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True, verbose_name='id в справочнике бота'),
        ),
        migrations.AddField(
            model_name='executor',
            name='territory',
            field=models.CharField(blank=True, max_length=120, verbose_name='территория'),
        ),
    ]
